# Sharing your book

以下の説明はダメ
標本サイズ30以上ならば大丈夫
正規性検定で正規性の帰無仮説が棄却されなかったら、正規分布モデルを使って良い

＊母集団分布の形状について何も情報がないならば、必要な標本サイズの上限は決まらなくなります。
＊身長なら正規分布モデルに従うことが和kる
＊母平均があなたの目的にとって適切な代表値なのかどうかをよく考えよ。
＊検定達は、確かに正規分布モデルを使って導出される検定法ですが、中心極限定理のお陰で、正規分布モデル自体が誤りになるような未知の母集団分布の場合であっても許容できる誤差の範囲内で使用可能な場合が結構沢山あります。(もちろんダメな場合もある。)
＊正規分布でないからノンパラ使おう（無条件では）はだめ
＊Mann-WhitneyのU検定のP値は

2つの母集団分布はぴったり等しい

という仮定を使って計算されるので、2群の優劣のために使用するのは危険な場合があります。

無条件では使えない使い方が難しい検定法なので注意が必要。Mann-WhitneyのU検定を使っている報告は粗探しをする必要があります。
T検定はウェルチをデフォルトで使う
＊例えば、ある特定目的のための2つの集団の比較で母平均の差の推定値を使うことが適切であるか、という問題は、その目的と2つの集団とデータの取得法に関する専門知識がないと手も足も出ない問題になります。統計学の使用では

Science before Statistics! 

という合言葉が必要。

*Use of nomality tests before t test
https://discourse.datamethods.org/t/reference-collection-to-push-back-against-common-statistical-myths/1787#use-of-normality-tests-before-t-tests-13

フローチャートに従って決めるなどは推奨されない。
→研究したいこと、見たいことは何かを考える
→研究分野に対する知識が重要。〇→XならAIにもできるし、言語研究の専門家でなくても分析ができてしまう。→自分の研究したいことは自分が一番よく理解しようという心構えが自分の分野の将来も守る
過去の研究や理論的背景から、母集団分布の形を考える

引用：https://biostatistics.ucdavis.edu/sites/g/files/dgvnsk4966/files/media/documents/Greenland.Advancing%20statistics%20reform%2C%20part%204.Slides%201-110%2C%2001%20June%202022.pdf